---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: 0.13.3
  interval: 1m0s
  targetNamespace: metallb-system
  releaseName: metallb
  install:
    createNamespace: true
  values:
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 172.18.255.1-172.18.255.254
