apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-release
  namespace: flux-system
spec:
  interval: 60m0s
  timeout: 3m
  wait: true
  path: ./apps/metallb/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: metallb-vars
