---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wgc-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/prod/wgc-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx-release
