apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wgc
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: 172.18.255.1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-weave-gitops
            port:
              number: 80
