apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx-release
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/ingress-nginx/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb-release
    - name: metallb-config
