---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: ${version}
  interval: 1m0s
  targetNamespace: metallb-system
  releaseName: metallb
  install:
    createNamespace: true
