apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/metallb
- ../../../apps/ingress-nginx
- ../../../apps/weave-gitops
  #- ../../../apps/kube-prometheus-stack
patchesStrategicMerge:
  - metallb-version.yaml
